#!/bin/bash

THIS=`dirname "$BASH_SOURCE"`

if [ -f "$HOME/.vimrc" ]; then
  echo $THIS
  cp -iv $THIS/.vimrc $HOME/.vimrc
  if ! [ -d "$HOME/.vim/undodir" ]; then
    mkdir -v $HOME/.vim/undodir
  fi
  if ! [ -d "$HOME/Templates" ]; then
    cp -irv $THIS/Templates $HOME
  fi
#elif [ $THIS/.vimrc -nt $HOME/.vimrc ]; then
#  cp -iv $THIS/.vimrc $HOME/.vimrc
else
  echo "Couldn't copy .vimrc"
fi

#cp -iv $HOME/myLinuxConfig/.bashrc $HOME/.bashrc
