#!/bin/bash

THIS=`dirname "$BASH_SOURCE"`

if [ -f "$HOME/.vimrc" ]; then
  echo $THIS
  ln -iv $THIS/.vimrc $HOME/.vimrc
  if ! [ -d "$HOME/.vim/undodir" ]; then
    mkdir -v $HOME/.vim/undodir
  fi
  if ! [ -d "$HOME/Templates" ]; then
    ln -iv $THIS/Templates $HOME/Templates
  fi
else
  echo "Something went wrong"
fi
